app:
  config:
    title: reviutils-fastapi
    description: ReviUtils相关功能fastapi接口文档
    version: demo
    root_path: #使用nginx反向代理时设置, "/api"
server:
  host: 0.0.0.0
  port: 8080
  reload: true
cors:
    allow_origins: ['*']
sqlalchemy:
  echo: True
database:
  sqlite:
    auth:
      url: "sqlite:///./databases/auth.sqlite3"
SECRET_KEY: beaa7dbf68bdf1a46298e5258629cdec898a16df57aeb133c63bdcd2b0476a81