app:
  config:
    title: reviutils-fastapi
    description: ReviUtils相关功能fastapi接口文档
    version: demo
    root_path: "/api" #使用nginx反向代理时设置, "/api"
server:
  host: 0.0.0.0
  port: 8080
  reload: false
cors:
    allow_origins: ['*']
sqlalchemy:
  echo: false
database:
  sqlite:
    auth:
      url: "sqlite:///./databases/auth.sqlite3"
SECRET_KEY: 